#!/bin/bash
local prefixed=0
local debug=0
local verbose=0
local namespace=default
if [[ ${K8S_ARGV:-} ]]; then
    for arg in ${K8S_ARGV}; do
        case ${arg} in
            --debug)
                debug=1
                ;;
            --namespace=*)
                namespace=${arg##*=}
                ;;
            --name=*)
                name=${arg##*=}
                ;;
            --id=*)
                id=${arg##*=}
                # forced append of - separator if none found
                if [[ -n "${id##*-}" ]]; then
                    id="${id}-"
                fi
                ;;
            --verbose)
                verbose=1
                ;;
            --prefixed)
                prefixed=1
                ;;
            --help)
                usage
                exit 0
                ;;

        esac
    done
fi
