#!/bin/bash

function make-yaml-stdio
{
    local k8scfgdir=${dir}/.k8s-cfg
    local cfgdir=${dir}/.cfg
    . ${k8scfgdir}/init
    . ${k8scfgdir}/flags

    if (( ! prefixed )); then
        local id=""
    fi
    local k8sprivatedir=$(readlink -f ${dir})/.private
    local kubeconfig=${k8sprivatedir}/.${master}.k8s-cfg

    clustercfg=$(base64 -w 0 ${kubeconfig})
    public=$(base64 -w 0 ~/.ssh/id_${ssh_key_type}.pub)
    private=$(base64 -w 0 ~/.ssh/id_${ssh_key_type})
    sed -r                                                                              \
        -e "s,\{repo\}(.*),${k8stestrepo}\\1,g"                                         \
        -e "s,app:.*${name}.*,app: ${id}${name},g"                                      \
        -e "s,namespace:.*${name}.*,namespace: ${namespace},g"                          \
        -e "s,secretName: *${name}-secret *\$,secretName: ${id}${name}-secret,g"        \
        -e "s,name: *${name}-secret,name: ${id}${name}-secret,g"                        \
        -e "s,name: *${name} *\$,name: ${id}${name},g"                                  \
        -e "s,kubeconfig:.*,kubeconfig: ${kubeconfig},g"                                \
        -e "s,authorized-keys:.*,authorized-keys: ${public},g"                          \
        -e "s,id-:.*,${ssh_key_type}: ${private},g"                                     \
        -e "s,id-.pub:.*,${ssh_key_type}.pub: ${public},g"
}

function make-yaml-call
{
    local inyaml=${1}
    make-yaml-stdio < ${inyaml}
}

function make-yaml
{
    make-yaml-call ${inyaml}
}
