#!/bin/bash

function make-yaml-stdio
{
    local k8scfgdir=${dir}/.k8s-cfg
    local cfgdir=${dir}/.cfg
    . ${k8scfgdir}/load-configuration

    . ${k8scfgdir}/flags

    if [[ ${id:-} ]] ; then
        local fromname=${name//${id}/}
        local fromnamespace=${namespace//${id}/}
        local toname=${id}${fromname}
        local tonamespace=${id}${fromnamespace}
    else
        local fromname=${name}
        local fromnamespace=${namespace}
        local toname=${id}${fromname}
        local tonamespace=${id}${fromnamespace}
    fi

    local k8sprivatedir=$(readlink -f ${dir})/.private
    local kubeconfig=${k8sprivatedir}/.${master}.k8s-cfg

    clustercfg=$(base64 -w 0 ${kubeconfig})
    public=$(base64 -w 0 ~/.ssh/${ssh_key_name}.pub)
    private=$(base64 -w 0 ~/.ssh/${ssh_key_name})

    sed -r                                                                              \
        -e "s,\{repo\}(.*),${k8srepo}\\1,g"                                             \
        -e "s,app: .*${fromname}.*,app: ${toname},g"                                    \
        -e "s,namespace: .*${fromnamespace}.*,namespace: ${tonamespace},g"              \
        -e "s,secretName: .*${fromname}-secret *\$,secretName: ${toname}-secret,g"      \
        -e "s,name: .*${fromname}-secret,name: ${toname}-secret,g"                      \
        -e "s,name: .*${fromname},name: ${toname},g"                                    \
        -e "s,kubeconfig: .*,kubeconfig: ${kubeconfig},g"                               \
        -e "s,authorized-keys: .*,authorized-keys: ${public},g"                         \
        -e "s,id-: .*,${ssh_key_name//_/-}: ${private},g"                               \
        -e "s,id-.pub: .*,${ssh_key_name//_/-}.pub: ${public},g"

}

function make-yaml-call
{
    local template=${1}
    make-yaml-stdio < ${template}
}

function make-yaml
{
    make-yaml-call ${template}
}
