#!/bin/bash
# id might be your initials or other distinguishing text for a
# process/rc,svc,pod,ep,namespace
# ssh_key_type for ssh key
# master /etc/host entry or DNS entry for access host to k8s cluster
# os_user user on the os on the k8s nodes.

function validate
{
    valid=$1
    eval "#!/bin/bash -x
    if [[ \${0} != /bin/bash ]]; then
        if [[ ! \${${valid}:-} ]]; then
            echo 'required [.cfg/mycfg] option: ${valid} not set';
            exit 3;
        fi;
    fi;
    #echo \${${valid}}
"
}

# validate id # optional
validate ssh_key_name
validate master
validate os_user
validate name
validate namespace
validate yaml
validate inyaml
validate hubuid
validate hubrepo
validate k8srepo
