#!/bin/bash
# id might be your initials or other distinguishing text for a
# process/rc,svc,pod,ep,namespace
# ssh_key_type for ssh key
# master /etc/host entry or DNS entry for access host to k8s cluster
# os_user user on the os on the k8s nodes.

mycfg=${dir}/.cfg/mycfg

if [[ ! -e ${mycfg:-} ]]; then
    echo "${mycfg} was not found. have you tailored the configuration to your requirements?"
    exit 3
fi

. ${mycfg}

function validate
{
    valid=$1
    eval "#!/bin/bash -x
    if [[ \${0} != /bin/bash ]]; then
        if [[ ! \${${valid}:-} ]]; then
            echo 'required [scripts/configure] option: ${valid} not set';
            exit 3;
        fi;
    fi;
    #echo \${${valid}}
"
}

validate id
validate ssh_key_type
validate master
validate os_user
validate name
validate yaml
validate inyaml
validate make_yaml_file
validate hubuid
validate k8srepo
validate hubrepo
export k8scfgdir=$(readlink -f ${dir}/.k8s-cfg)
export k8scfgbin=$(readlink -f ${k8scfgdir}/../bin)
export kubectlbin=${k8scfgbin}/kubectl
export kubeconfig=${dir}/.private/.${master}.k8s-cfg
